### ISSUE TITLE
Code about STM-SIM

### ISSUE THREAD

**Issue by ghost** [Zhijin-Ge/STM#2]
Hello, I found that if I follow the method in Algorithm 1 in the paper to update the adversarial samples on STM-SIM, the result will be a little bit different from the result in the paper, can you update the part about STM-SIM in the code, so that I can do the reproduction. :)

**Comment by Zhijin-Ge** [comment]
Thanks for your interest in our work. Since I couldn't find the previous code, I rewrote it, and this code should be able to reproduce the results from the paper. 
![STM-SIM](https://github.com/Zhijin-Ge/STM/assets/42350897/82de382e-a7af-43a1-bedf-4d4bfe889767)
Additionally, I have updated "verify.py" which requires changing gt to gt+1 as the ground truth label when validating the adversarial trained model. More information can be found in issue 1. We hope this information is useful to you!
